#!/bin/bash
# This hook is sourced after every virtualenv is activated.
export PS1=$ORIG_PS1

venv=$(basename $VIRTUAL_ENV)
path=$(find $HOME/src -maxdepth 3 -wholename "*/$venv" -print0)

[ -n "$path" ] && cd $path
